print('{1} {0}'.format('one', 'two'))
print('{:10}'.format('test'))
print('{:^20}'.format('test'))
print('{:_<30}'.format('test'))
print('{:.7}'.format('grzegrzółka'))
print('{:+d}'.format(48))
